stages:
  preprocess_train:
    cmd: python src\preprocess_data.py -s 1 -i data/raw/1_2024-05-07_23-07.csv data/raw/2_2024-05-07_23-16.csv data/raw/3_2024-05-07_23-23.csv
  preprocess_test:
    cmd: python src\preprocess_data.py -s 0 -i data/raw/1_2024-05-07_23-07.csv data/raw/2_2024-05-07_23-16.csv data/raw/3_2024-05-07_23-23.csv
  train_model:
    cmd: python src\train_model.py -m models/linear_regression_v01.joblib
  test_model:
    cmd: python src\test_model.py -m models/linear_regression_v01.joblib